### ISSUE TITLE
Support images hosted on Cloudinary

### ISSUE THREAD

**Issue by stevegrunwell** [copyhackers/airstory-wp#27]
In my original testing, all images seemed to be coming from https://images.airstory.co, so the pattern for "hey, this image needs to be sideloaded" (within `Formatting\sideload_all_images()`) was for that specific domain.

As it turns out, many images are hosted on Cloudinary.com ([example image](https://res.cloudinary.com/airstory/image/upload/c_scale,w_0.1/v1/prod/i1488505393672df7b2-f0dc-4c27-96dc-e68556093b42/Screen%20Shot%202017-03-02%20at%205.17.49%20PM.png)) — it's unclear at this point exactly why some images go to Cloudinary v. images.airstory.co (perhaps if a transformation is applied?), but the plugin needs to sideload media from both sources. That means matching `res.cloudinary.com/airstory` as an image source and ensuring the original image is imported as well as any cropped version.

**Comment by norcross** [comment]
should we just check for any URLs that aren't the WP one?

**Comment by stevegrunwell** [comment]
That could cause issues if, for instance, an author is using media they already host somewhere that's suitable for production. I'm thinking expand the regex for the pattern matching to be something like:

```php
$domains = array( 'images.airstory.co', 'res.cloudinary.com/airstory' );

/**
 * Filter the image hosts that should be side-loaded into WordPress.
 *
 * @param array $domains Domains/paths that should be side-loaded into WordPress.
 */
$domains = apply_filters( 'airstory_image_hosts', $domains );

// If no domains should be side-loaded, return early.
if ( empty( $domains ) ) {
  return;
}

// Escape the domains for regular expressions.
foreach ( (array) $domains as $index => $domain ) {
  $domains[ $index ] = preg_quote( untrailingslashit( $domain ), '/' );
}

$pattern = '/^https?:\/\/(' . implode( '|', $domains ) . '\//i';
```

That way, users who *wanted* to include other domains could, but we're not defaulting to "let's download _all the things_".

**Comment by norcross** [comment]
maybe pull all the images via DOMDocument, then do a `parse_url` to check against a list of domains we wanna grab?

**Comment by stevegrunwell** [comment]
...I hate when you're right. Some normalization to account for capitalization will be necessary, but that's a good route to go.

Edit: and by "hate", I mean "I'm glad you're there to provide good input" 👍

**Comment by norcross** [comment]
everything's comin' up Milhouse!

**Comment by stevegrunwell** [comment]
I got some background information from @stevendluke — apparently all of the media is hosted at Cloudinary at this point, but images.airstory.co masks that. Older content may still reference the res.cloudinary.com URL, which is why Lance (one of the OG Airstory users) is getting those URLs but I'm not.

Using the example image from earlier, these two URLs are equivalent:

* https://images.airstory.co/c_scale,w_0.1/v1/prod/i1488505393672df7b2-f0dc-4c27-96dc-e68556093b42/Screen%20Shot%202017-03-02%20at%205.17.49%20PM.png
* https://res.cloudinary.com/airstory/image/upload/c_scale,w_0.1/v1/prod/i1488505393672df7b2-f0dc-4c27-96dc-e68556093b42/Screen%20Shot%202017-03-02%20at%205.17.49%20PM.png
