### ISSUE TITLE
Include MU plugins in system report

### ISSUE THREAD

**Issue by stevegrunwell** [copyhackers/airstory-wp#71]
On the Tools > Airstory page, we generate a list of system details, including active plugins (see #34). However, this list doesn't appear to include must-use (MU) plugins, which can be just as impactful on a site.

**Comment by norcross** [comment]
I have code for this somewhere

**Comment by stevegrunwell** [comment]
I was mistaken, this is absolutely already happening: https://github.com/liquidweb/airstory-wp/blob/develop/includes/tools.php#L367
