### ISSUE TITLE
CORS error when publishing from Airstory to WordPress

### ISSUE THREAD

**Issue by stevegrunwell** [copyhackers/airstory-wp#74]
An Airstory customer has had trouble publishing from Airstory to WordPress, and was kind enough to pass along screenshots of the JavaScript console while using the Airstory app, which contained the following error:

> XMLHttpRequest cannot load https://www.example.com/wp-json/airstory/v1/webhook. Redirect from 'https://www.example.com/wp-json/airstory/v1/webhook' to 'https://www.example.com/wp-json/airstory/v1/webhook' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://app.airstory.co' is therefore not allowed access.

The only thing different between the two paths is the trailing slash (this particular site 301 redirects requests to the version with the trailing slash).

Two possible solutions here:

1. Determine if the WordPress site is enforcing trailing slashes and, if so, ensure it's present when registering a connection with Airstory.
    * This would be more fragile, as these trailing slashes are often enforced at the server level rather than within WordPress.
2. Attempt to register the correct CORS headers to accept requests from https://app.airstory.co.

**Comment by norcross** [comment]
this may help https://joshpress.net/access-control-headers-for-the-wordpress-rest-api/

**Comment by notagrouch** [comment]
Any chance this will get an update soon? Not sure how to help or request help, the ticket at wordpress.org seems to have been forgotten.

**Comment by stevegrunwell** [comment]
@notagrouch,

My apologies, notifications on [the WordPress.org ticket](https://wordpress.org/support/topic/wordpress-could-not-be-reached/) didn't arrive in my inbox as they're supposed to. I've updated the ticket there.

**Comment by stevegrunwell** [comment]
I've _finally_ been able to dedicate some time to dig into this, and have been able to reproduce the issue in a sandbox site by forcing a trailing slash on requests in a way similar to how a web server would:

Code to enforce this behavior (which I've dropped in an MU plugin in my test environment):
```php
<?php

/**
 * Force all REST API requests to use a trailing slash.
 */
add_action( 'rest_api_init', function () {
    if ( '/' !== substr( $_SERVER['REQUEST_URI'], -1, 1 ) ) {
        wp_redirect( trailingslashit( $_SERVER['REQUEST_URI'] ) );
        exit;
    }
} );
```

The WP REST API handles trailing slashes properly ([see `rest_api_loaded()`](https://developer.wordpress.org/reference/functions/rest_api_loaded/), which calls `untrailingslashit()` on the REST URL before parsing requests); the challenge is that a global, web server-level redirect to the trailing slash form of a URI is beyond the control of the plugin. ([This post by @collinbarrett demonstrates the _proper_ redirect rule](https://collinmbarrett.com/nginx-trailing-slashes-wordpress/)).

The following table illustrates the possible combinations: "Airstory target" refers to the URI stored by Airstory, whilst "Effective path" is the resolved URI, after any redirects.

Airstory target | Effective path | Working? | Note
-------------- | ---------------- | -------- | ----
/webhook | /webhook | yes | Default, expected configuration
/webhook | /webhook/ | no | 3xx redirect, causing CORS issue
/webhook/ | /webhook | yes | WP REST API accounting for trailing slashes
/webhook/ | /webhook/ | yes | Matching path, no redirect necessary

While we can introduce `Access-Control-Allow-Origin` headers to ensure requests to the webhook are coming from https://app.airstory.co (see #75), that won't help sites enforcing trailing slashes at the web server level (since the redirect will be returned before the request ever reaches the application). A more useful approach would be to determine the effective webhook endpoint and, if necessary, update the Airstory target accordingly.

**Comment by stevegrunwell** [comment]
Now that #75 and #77 have been merged, [I've tagged a beta release of version 1.1.5](https://github.com/liquidweb/airstory-wp/releases/tag/v1.1.5-beta) that should prevent this from happening to users moving forward.

I'll be reaching out to the various tickets on the WordPress.org repo and Airstory support momentarily to direct users to the beta release.

**Comment by stevegrunwell** [comment]
I've not heard back in either the affirmative nor negative from the support threads, but in the interest of releasing 1.1.5 I'm closing this ticket.
